### ISSUE TITLE
gopass ls of an unavailable entry causes nil pointer dereference

### ISSUE THREAD

**Issue by zabil** [justwatchcom/gopass#182]
##Steps to reproduce

```
✗ gopass ls anentrynotthere
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x56541a]

goroutine 1 [running]:
github.com/justwatchcom/gopass/tree/simple.(*Folder).SetRoot(0x0, 0x7ffe20de4101)
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/tree/simple/folder.go:238 +0xa
github.com/justwatchcom/gopass/action.(*Action).List(0xc420010de0, 0xc4200908c0, 0xc420052c38, 0xc420052c38)
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/action/list.go:57 +0x4e8
github.com/justwatchcom/gopass/action.(*Action).List-fm(0xc4200908c0, 0x0, 0x0)
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/main.go:369 +0x34
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.HandleAction(0x67ade0, 0xc4200192f0, 0xc4200908c0, 0xc42001a700, 0x0)
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.Command.Run(0x6c67f4, 0x4, 0x0, 0x0, 0xc420019640, 0x1, 0x1, 0x6c8a43, 0xd, 0x0, ...)
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.(*App).Run(0xc42009c9c0, 0xc420010270, 0x3, 0x3, 0x0, 0x0)
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/home/zabilcm/go/src/github.com/justwatchcom/gopass/main.go:551 +0x4b6a
```
```
✔︎ sam (master) ✗ gopass --version
gopass HEAD (n/a ) go1.8.3

```
```
✗ uname -smovri
Linux 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 GNU/Linux

```

**Comment by dominikschulz** [comment]
Super strange, there is a `if subtree == nil` check guarding these lines. Looking into it ...
