### ISSUE TITLE
gopass init returns a "runtime error: slice bounds out of range"

### ISSUE THREAD

**Issue by Dr-Terrible** [justwatchcom/gopass#515]
The `gopass init` command returns runtine errors when it is supplied with "." as parameters: 

```shell
$ gopass init --path .
[init] Initializing a new password store ...
Please select a private key for encrypting secrets:
[0] 0xXXXXXXXXXXXXXXXX - Test (signing) <test@email.com>
Please enter the number of a key (0-0) [0]: 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/justwatchcom/gopass/utils/fsutil.CleanPath(0x7fff6eef36cf, 0x1, 0x0, 0xc42002034b)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/utils/fsutil/fsutil.go:27 +0x243
github.com/justwatchcom/gopass/store/sub.New(0x0, 0x0, 0x7fff6eef36cf, 0x1, 0x0)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/store/sub/store.go:35 +0x3f
github.com/justwatchcom/gopass/store/root.(*Store).Init(0xc420242000, 0xd20a00, 0xc420234d20, 0x0, 0x0, 0x7fff6eef36cf, 0x1, 0xc4201f9cf0, 0x1, 0x1, ...)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/store/root/init.go:16 +0x59
github.com/justwatchcom/gopass/action.(*Action).init(0xc4200f4100, 0xd20a00, 0xc420234d20, 0x0, 0x0, 0x7fff6eef36cf, 0x1, 0xc4201f9e00, 0xc420080030, 0x1, ...)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/action/init.go:67 +0x107
github.com/justwatchcom/gopass/action.(*Action).Init(0xc4200f4100, 0xd20a00, 0xc420234d20, 0xc420298140, 0xc420234a20, 0xc4201f9eb0)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/action/init.go:44 +0x1f1
main.main.func45(0xc420298140, 0x0, 0xc420298140)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/main.go:689 +0x79
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.HandleAction(0x92f420, 0xc42000a660, 0xc420298140, 0xc420060300, 0x0)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:485 +0xd2
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.Command.Run(0x9ccdb0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa0c765, 0x1e, 0x0, ...)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/command.go:193 +0xa99
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.(*App).Run(0xc42024a340, 0xc420080000, 0x4, 0x4, 0x0, 0x0)
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:250 +0x758
main.main()
	/var/tmp/portage/app-admin/gopass-1.6.2/work/gopath/src/github.com/justwatchcom/gopass/main.go:1054 +0x73e0
```

**Comment by dominikschulz** [comment]
Wow, nice find. How do you setup the fuzz tests?

Anyway, I'll have a look at this bug.
