### ISSUE TITLE
bash autocomplete segmentation violation

### ISSUE THREAD

**Issue by pontostroy** [justwatchcom/gopass#746]
go 1.10
gopass 94c296e75310d85e087df5df2ea609349fe47eab
gopass + TAB
```
./gopass panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x92eaa7]

goroutine 1 [running]:
github.com/justwatchcom/gopass/pkg/store/sub.(*Store).List(0x0, 0xdb7b80, 0xc420177b60, 0x0, 0x0, 0x9, 0x0, 0x0, 0x0, 0x0)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/pkg/store/sub/list.go:15 +0x37
github.com/justwatchcom/gopass/pkg/store/root.(*Store).Tree(0xc4200bfd40, 0xdb7b80, 0xc420177b60, 0xd0cefb, 0x9, 0x0, 0x0)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/pkg/store/root/list.go:55 +0x1ad
github.com/justwatchcom/gopass/pkg/store/root.(*Store).List(0xc4200bfd40, 0xdb7b80, 0xc420177b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/pkg/store/root/list.go:17 +0x43
github.com/justwatchcom/gopass/pkg/action.(*Action).Complete(0xc4202d8e70, 0xdb7b80, 0xc420177b60, 0xc42010b340)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/pkg/action/completion.go:28 +0x67
main.setupApp.func1(0xc42010b340)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/app.go:56 +0x72
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.ShowCompletions(0xc42010b340)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/help.go:224 +0x49
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.checkCompletions(0xc42010b340, 0xc42010b340)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/help.go:334 +0x7c
github.com/justwatchcom/gopass/vendor/github.com/urfave/cli.(*App).Run(0xc4201961c0, 0xc4200c0000, 0x1, 0x2, 0x0, 0x0)
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/vendor/github.com/urfave/cli/app.go:206 +0x351
main.main()
        /home/pontostroy/GO/GOPATH/src/github.com/justwatchcom/gopass/main.go:63 +0x2d7

```

**Comment by dominikschulz** [comment]
Thank you for reporting this issue. I've changed some parts of the initialization workflow and forgot to guard the completion funcs. Will be fixed soon.
